<?php 

class Tagger {
    public $map = array();
    static private $stopWords = array(
        "a",
        "acuerdo",
        "adelante",
        "ademas",
        "además",
        "adrede",
        "ahi",
        "ahí",
        "ahora",
        "al",
        "alli",
        "allí",
        "alrededor",
        "antano",
        "antaño",
        "ante",
        "antes",
        "apenas",
        "aproximadamente",
        "aquel",
        "aquél",
        "aquella",
        "aquélla",
        "aquellas",
        "aquéllas",
        "aquello",
        "aquellos",
        "aquéllos",
        "aqui",
        "aquí",
        "arriba",
        "abajo",
        "asi",
        "así",
        "aun",
        "aún",
        "aunque",
        "b",
        "bajo",
        "bastante",
        "bien",
        "breve",
        "c",
        "casi",
        "cerca",
        "claro",
        "como",
        "cómo",
        "con",
        "conmigo",
        "contigo",
        "contra",
        "cual",
        "cuál",
        "cuales",
        "cuáles",
        "cuando",
        "cuándo",
        "cuanta",
        "cuánta",
        "cuantas",
        "cuántas",
        "cuanto",
        "cuánto",
        "cuantos",
        "cuántos",
        "d",
        "de",
        "debajo",
        "del",
        "delante",
        "demasiado",
        "dentro",
        "deprisa",
        "desde",
        "despacio",
        "despues",
        "después",
        "detras",
        "detrás",
        "dia",
        "día",
        "dias",
        "días",
        "donde",
        "dónde",
        "dos",
        "durante",
        "e",
        "el",
        "él",
        "ella",
        "ellas",
        "ellos",
        "en",
        "encima",
        "enfrente",
        "enseguida",
        "entre",
        "es",
        "esa",
        "ésa",
        "esas",
        "ésas",
        "ese",
        "ése",
        "eso",
        "esos",
        "ésos",
        "esta",
        "está",
        "ésta",
        "estado",
        "estados",
        "estan",
        "están",
        "estar",
        "estas",
        "éstas",
        "este",
        "éste",
        "esto",
        "estos",
        "éstos",
        "ex",
        "excepto",
        "f",
        "final",
        "fue",
        "fuera",
        "fueron",
        "g",
        "general",
        "gran",
        "h",
        "ha",
        "habia",
        "había",
        "habla",
        "hablan",
        "hace",
        "hacia",
        "han",
        "hasta",
        "hay",
        "horas",
        "hoy",
        "i",
        "incluso",
        "informo",
        "informó",
        "j",
        "junto",
        "k",
        "l",
        "la",
        "lado",
        "las",
        "le",
        "lejos",
        "lo",
        "los",
        "luego",
        "m",
        "mal",
        "mas",
        "más",
        "mayor",
        "me",
        "medio",
        "mejor",
        "menos",
        "menudo",
        "mi",
        "mí",
        "mia",
        "mía",
        "mias",
        "mías",
        "mientras",
        "mio",
        "mío",
        "mios",
        "míos",
        "mis",
        "mismo",
        "mucho",
        "muy",
        "n",
        "nada",
        "nadie",
        "ninguna",
        "no",
        "nos",
        "nosotras",
        "nosotros",
        "nuestra",
        "nuestras",
        "nuestro",
        "nuestros",
        "nueva",
        "nuevo",
        "nunca",
        "o",
        "os",
        "otra",
        "otros",
        "p",
        "pais",
        "paìs",
        "para",
        "parte",
        "pasado",
        "peor",
        "pero",
        "poco",
        "podría",
        "por",
        "porque",
        "pronto",
        "proximo",
        "próximo",
        "puede",
        "q",
        "qeu",
        "que",
        "qué",
        "quien",
        "quién",
        "quienes",
        "quiénes",
        "quiza",
        "quizá",
        "quizas",
        "quizás",
        "r",
        "raras",
        "repente",
        "s",
        "salvo",
        "se",
        "sé",
        "segun",
        "según",
        "ser",
        "sera",
        "será",
        "si",
        "sí",
        "sido",
        "siempre",
        "sin",
        "sobre",
        "solamente",
        "solo",
        "sólo",
        "son",
        "soyos",
        "su",
        "supuesto",
        "sus",
        "suya",
        "suyas",
        "suyo",
        "t",
        "tal",
        "tambien",
        "también",
        "tampoco",
        "tarde",
        "te",
        "temprano",
        "ti",
        "tiene",
        "todavia",
        "todavía",
        "todo",
        "todos",
        "tras",
        "tu",
        "tú",
        "tus",
        "tuya",
        "tuyas",
        "tuyo",
        "tuyos",
        "u",
        "un",
        "una",
        "unas",
        "uno",
        "unos",
        "usted",
        "ustedes",
        "v",
        "veces",
        "vez",
        "vosotras",
        "vosotros",
        "vuestra",
        "vuestras",
        "vuestro",
        "vuestros",
        "w",
        "x",
        "y",
        "ya",
        "yo",
        "z",
        "http",
        "https",
        "ftp",
        "www",
        "com",
        "net",
        "org"
    );
    static private $chars = array('.', ',', ':', ';', '-', '_', '/', '"', '\'', '\\', '!',
                                  '#', '$', '%', '&', '(', ')', '=', '+', '¿', '?', '¡',
                                  '*', '[', ']', '{', '}' ,'@', '°', '“', '”', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9);

    static private function tokenExists($tok, $list) {
        $token = false;
        $max = 100;

        foreach ($list as $i => $item) {
            $ratio = round(100 * levenshtein($tok, $item) / max(strlen($tok), strlen($item)));

            if ($ratio < 40 && $ratio < $max) {
                $token = $item;
                $max = $ratio;
            }
        }

        return $token;
    }

    public function delete() {
        $this->map = array();
    }

    public function tokenize($text, $weight = 1) {
        $text = split(' ', str_replace(self::$chars, ' ', $text));
        $total = count($text);

        for ($i = 0; $i < $total; ++$i) {
            $tok = strtolower($text[$i]);

            // Discard token
            if (strlen($tok) < 2 || in_array($tok, self::$stopWords)) {
                unset($text[$i]);
            } else {
                // Insert token in list
                if ($tmp = self::tokenExists($tok, array_keys($this->map))) {
                    $this->map[$tmp] = $this->map[$tmp] + $weight;
                } else {
                    $this->map[$tok] = $weight;
                }
            }
        }

        // Sort keys
        arsort($this->map);

        return $this->map;
    }
}
